CAPAggregator/grails-app/controllers/capcollator/HomeController.groovy
package capcollator

import grails.plugin.springsecurity.annotation.Secured
import grails.converters.JSON

class HomeController {

  def eventService

  def index() { 
    // def result = [:]
    // result.statsCache = eventService.getStatsCache()
    // result
    redirect(controller:'subscriptions', action:'index');
  }

  def status() { 
    def result = [:]
    result.statsCache = eventService.getStatsCache()
    result
  }

  def topic() {
    log.debug("Topic: ${params}");
    def result = [:]
    result
  }

  def about() {
    def result = [:]
    result
  }


  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def login() {
    redirect(controller:'subscriptions', action:'index');
  }

  def explorer1() {
    def result=[:]
    result
  }

  def info() {
    def result=[:]
    result.headers=[:]
    request.getHeaderNames().each { header_name ->
      result.headers[header_name] = request.getHeader(header_name);
    }
    render result as JSON
  }
}

CAPAggregator/grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>

<g:if test="${!grailsApplication.config.gtmcode.equals('none')}">
  <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${grailsApplication.config.gtmcode}');</script>
  <!-- End Google Tag Manager -->
</g:if>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <meta name="description" content="CAP Aggregator is a tool for aggregating and indexing Common Alerting Protocol alerts into a single searchable resource that can be used to build useful emergency alerting applications. You can think of CAPAggregator as middleware that sits between CAP event publishers and CAP event consumers."/>

    <title>
        <g:layoutTitle default="CAP Aggregator - Emergency Alert Aggregation Middleware"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

  <g:if test="${!grailsApplication.config.gtmcode.equals('none')}">
    <!-- Google Tag Manager (noscript) -->
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=${grailsApplication.config.gtmcode}" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
  </g:if>

  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <g:link controller="home" action="index" class="navbar-brand">CAPAggregator <g:meta name="info.app.version"/></g:link>
      </div>

      <div class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
          <sec:ifLoggedIn>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><sec:username/><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><g:link controller="home" action="profile">Profile</g:link></li>
                <li class="divider"></li>
                <li><g:link controller="home" action="logout">Logout</g:link></li>
              </ul>
            </li>
          </sec:ifLoggedIn>
          <sec:ifNotLoggedIn>
            <li class="${controllerName=='home' && actionName=='login' ? 'active' : ''}"><g:link controller="home" action="login">Login</g:link></li>
          </sec:ifNotLoggedIn>
        </ul>
      </div>


      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="${controllerName=='home' && actionName=='index' ? 'active' : ''}"><g:link controller="home" action="index">Home</g:link></li>
          <li class="${controllerName=='alert' && actionName=='nearby' ? 'active' : ''}"><g:link controller="alert" action="nearby">Nearby</g:link></li>
          <li class="${controllerName=='home' && actionName=='about' ? 'active' : ''}"><g:link controller="home" action="about">About</g:link></li>
          <sec:ifLoggedIn>
            <sec:ifAnyGranted roles="ROLE_ADMIN">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="${controllerName=='admin' && actionName=='registerConsumer' ? 'active' : ''}"><g:link controller="admin" action="registerConsumer">Register Consumer</g:link></li>
                  <li class="${controllerName=='admin' && actionName=='reindex' ? 'active' : ''}"><g:link controller="admin" action="reindex">Reindex</g:link></li>
                  <li class="${controllerName=='admin' && actionName=='syncSubList' ? 'active' : ''}"><g:link controller="admin" action="syncSubList">Load Subscription List</g:link></li>
                </ul>
              </li>
            </sec:ifAnyGranted>
            <li class="${controllerName=='subscriptions' && actionName=='index' ? 'active' : ''}"><g:link controller="subscriptions" action="index">Subscriptions</g:link></li>
          </sec:ifLoggedIn>
          <li class="${controllerName=='home' && actionName=='topic' ? 'active' : ''}"><g:link controller="subscriptions" action="details" id="unfiltered" params="${[tag:'mappable']}">Unfiltered</g:link></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  
  <g:layoutBody/>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.4.0/leaflet.css" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.4.0/leaflet.js"></script>

  <asset:javascript src="application.js"/>
  <asset:deferredScripts/>
</body>
</html>

CAPAggregator/grails-app/views/layouts/nojsmain.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="CAP Aggregator"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>
<body>

  <div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">CAPAggregator</a>
      </div>

      <div class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
          <sec:ifLoggedIn>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><sec:username/><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><g:link controller="home" action="profile">Profile</g:link></li>
                <li class="divider"></li>
                <li><g:link controller="home" action="logout">Logout</g:link></li>
              </ul>
            </li>
          </sec:ifLoggedIn>
          <sec:ifNotLoggedIn>
            <li class="${controllerName=='home' && actionName=='login' ? 'active' : ''}"><g:link controller="home" action="login">Login</g:link></li>
          </sec:ifNotLoggedIn>
        </ul>
      </div>


      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="${controllerName=='home' && actionName=='index' ? 'active' : ''}"><g:link controller="home" action="index">Home</g:link></li>
          <sec:ifLoggedIn>
            <sec:ifAnyGranted roles="ROLE_ADMIN">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="${controllerName=='admin' && actionName=='registerConsumer' ? 'active' : ''}"><g:link controller="admin" action="registerConsumer">Register Consumer</g:link></li>
                  <li class="${controllerName=='admin' && actionName=='reindex' ? 'active' : ''}"><g:link controller="admin" action="reindex">Reindex</g:link></li>
                  <li class="${controllerName=='admin' && actionName=='syncSubList' ? 'active' : ''}"><g:link controller="admin" action="syncSubList">Load Subscription List</g:link></li>
                </ul>
              </li>
            </sec:ifAnyGranted>
            <li class="${controllerName=='subscriptions' && actionName=='index' ? 'active' : ''}"><g:link controller="subscriptions" action="index">Subscriptions</g:link></li>
          </sec:ifLoggedIn>
          <li class="${controllerName=='home' && actionName=='topic' ? 'active' : ''}"><g:link controller="home" action="topic" id="unfiltered">Unfiltered</g:link></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  
  <g:layoutBody/>

  <asset:deferredScripts/>
</body>
</html>