CAPAggregator/grails-app/domain/capcollator/Subscription.groovy
package capcollator

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes='subscriptionId')
@ToString(includes='subscriptionId', includeNames=true, includePackage=false)
class Subscription {

  private static final long serialVersionUID = 1

  String id
  String subscriptionId
  String subscriptionName
  String subscriptionDescription
  String subscriptionUrl
  String filterType
  String filterGeometry

  String languageOnly
  String highPriorityOnly
  String officialOnly
  String xPathFilter
  String xPathFilterId

  String feedXmlTemplate
  Long feedItemLimit


  String notes

  static transients = []

  static hasMany = [
    hooks:WebHook
  ]

  static mappedBy = [
    hooks:'ownerSubscription'
  ]


  static constraints = {
             subscriptionId blank: false, nullable: false, unique: true
           subscriptionName blank: false, nullable: false
    subscriptionDescription blank: false, nullable: true
            subscriptionUrl blank: true, nullable: false
                 filterType blank: true, nullable: true
             filterGeometry blank: true, nullable: true
                      notes blank: true, nullable: true
               languageOnly blank: true, nullable: true
           highPriorityOnly blank: true, nullable: true
               officialOnly blank: true, nullable: true
                xPathFilter blank: true, nullable: true
              xPathFilterId blank: true, nullable: true
            feedXmlTemplate blank: true, nullable: true
              feedItemLimit blank: true, nullable: true
  }

  static mapping = {
    table 'cc_sub'
                         id column: 'sub_id', generator: 'uuid', length:36
             subscriptionId column: 'sub_txt_id'
           subscriptionName column: 'sub_name'
    subscriptionDescription column: 'sub_desc'
            subscriptionUrl column: 'sub_url'
             filterGeometry column: 'sub_filter_geom', type:'text'
               languageOnly column: 'sub_filter_lang'
           highPriorityOnly column: 'sub_filter_high_prio'
               officialOnly column: 'sub_filter_official'
                xPathFilter column: 'sub_filter_xpath'
              xPathFilterId column: 'sub_filter_xpathid'
            feedXmlTemplate column: 'sub_feed_xml_template', type:'text'
              feedItemLimit column: 'sub_feed_item_limit'
  }

}

CAPAggregator/grails-app/controllers/capcollator/AdminController.groovy
package capcollator

import grails.plugin.springsecurity.annotation.Secured
import static grails.async.Promises.*

class AdminController {

  def CAPIndexingService
  def subsImportService

  def index() { 
  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def registerConsumer() { 
  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def reindex() { 
    log.debug("AdminController::Reindex");
    CAPIndexingService.reindexSubscriptions()
    redirect(controller:'home',action:'index');
  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def syncSubList() {
    if (params.subUrl) {
      String target_url = params.subUrl
      log.debug("Attempting to parse list of subs from \"${target_url}\"");

      def import_promise = task {
        subsImportService.loadSubscriptionsFrom(target_url)
      }

      import_promise.onComplete {
        log.debug("subsImportService.loadSubscriptionsFrom - completed");
      }

      import_promise.onError { Throwable err ->
        println "An error occured ${err.message}"
      }

      log.debug("Started background loader task");
    }

    return [status:subsImportService.getStatus()];

  }

}

CAPAggregator/grails-app/controllers/capcollator/SubscriptionsController.groovy
package capcollator

import grails.plugin.springsecurity.annotation.Secured
import grails.rest.RestfulController 
import grails.converters.XML
import java.nio.charset.Charset

class SubscriptionsController {

  static responseFormats = [
        details: ['html', 'atom', 'rss']
  ]

  def CAPIndexingService
  def ESWrapperService

  def index() { 
    def result=[:]
    def qry_params = [:]
    def base_sub_qry = 'from Subscription as s'

    if ( ( params.q != null ) && ( params.q.length() > 0 ) ) {
      base_sub_qry += ' where lower(s.subscriptionId) like :a or lower(s.subscriptionName) like :a or lower(s.subscriptionUrl) like :a'
      qry_params.a = "%${params.q.toLowerCase()}%".toString()
    }
    def order_by_clause = ' order by s.id'

    def select_control_params = [
      max: params.max ?: 10,
      offset: params.offset ?: 0
    ]

    result.totalSubscriptions = Subscription.executeQuery('select count(s) '+base_sub_qry,qry_params)[0]
    result.subscriptions = Subscription.executeQuery('select s '+base_sub_qry+order_by_clause,qry_params,select_control_params)

    log.debug("found ${result.totalSubscriptions} feeds");

    result

  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def touch() {
    log.debug("Touch subscription ${params.id}");
    def sub=Subscription.get(params.id)
    sub.notes="${System.currentTimeMillis()}"
    sub.save(flush:true, failOnError:true);
    redirect(action:'index');
  }

  def details() {
    def result=[:]
    result.subscription = Subscription.findBySubscriptionId(params.id)

    response.characterEncoding = 'UTF-8'

    log.debug("Charset: ${Charset.defaultCharset().name()} encoding:${System.getProperty("file.encoding")}");
    result.subscription?.hooks.each { hook ->
      // This is a bit icky - it's done to eagerly fetch the hooks
      log.debug("Hook : ${hook}");
    }

    log.debug("Subscriptions::details() ${params} ${response.format}")

    List<String> query_clauses = []
    query_clauses.add('{ "match": { "AlertMetadata.MatchedSubscriptions": "'+params.id+'"} }')

    if ( params.q ) {
      query_clauses.add('{"simple_query_string": { "query":"'+params.q+'" } }')
    }

    params.each { k,v ->
      if ( k == 'tag' ) {
        query_clauses.add('{ "match" : { "AlertMetadata.tags":"'+v+'" } }');
      }
    }

    log.debug("Joined query clauses: ${query_clauses.join(',')}");

    String index_to_search = 'alerts';
    String es_query = '''{
         "bool": {
           "must": [ 
             '''+query_clauses.join(',\n')+'''
           ]
         } 
     }'''

    result.baseurl = grailsApplication.config.SystemBaseURL
    result.max = params.max ? Integer.parseInt(params.max) : 10;
    result.offset = params.offset ? Integer.parseInt(params.offset) : 0;

    try {
      result.latestAlerts = ESWrapperService.searchJson(index_to_search,
                                                        es_query,
                                                        result.offset,
                                                        result.max,
                                                        'evtTimestamp', 'desc');

      if ( result.latestAlerts != null ) {
        result.totalAlerts = result.latestAlerts.resultsTotal
        result.rows = result.latestAlerts.hits
      }
    }
    catch ( Exception e ) {
      log.error("Problem running ES Query to find alerts for sub query ${e.message}",e);
    }


    respond result
  }

  def rss() {
    def result=[:]
    result.subscription = Subscription.findBySubscriptionId(params.id)

    response.characterEncoding = 'UTF-8'

    def query_clause='';
    if ( params.q ) {
      query_clause = ',{"simple_query_string": { "query":"'+params.q+'" } }'
    }
    String[] index_to_search = 'alerts'
    String es_query = '''{
      "query": {
         "bool": {
           "must": [ 
             { "match": { "AlertMetadata.MatchedSubscriptions": "'''+params.id+'''"} }
             '''+query_clause+'''
           ]
         } 
       }
     }'''

    result.max = params.max ? Integer.parseInt(params.max) : 10;
    result.offset = params.offset ? Integer.parseInt(params.offset) : 0;

    try {
      result.latestAlerts = ESWrapperService.searchJson(index_to_search,es_query,result.offset,result.max,'evtTimestamp','desc');
      result.totalAlerts = result.latestAlerts?.resultsTotal
      result.rows = buildSubscriptionInfo(result.latestAlerts.hits)
    }
    catch ( Exception e ) {
      log.error("Problem with query",e);
    }

    render(template:'/subscriptions/rss', model:[result:result],contentType: "text/xml", encoding: "UTF-8",  contextPath: '/')
  }

  def atom() {
    def result=[:]
    result.subscription = Subscription.findBySubscriptionId(params.id)

    response.characterEncoding = 'UTF-8'

    def query_clause='';
    if ( params.q ) {
      query_clause = ',{"simple_query_string": { "query":"'+params.q+'" } }'
    }
    String[] indexes_to_search = [ 'alerts' ]
    String es_query = '''{
         "bool": {
           "must": [ 
             { "match": { "AlertMetadata.MatchedSubscriptions": "'''+params.id+'''"} }
             '''+query_clause+'''
           ]
         } 
       }'''

    result.max = params.max ? Integer.parseInt(params.max) : 10;
    result.offset = params.offset ? Integer.parseInt(params.offset) : 0;

    try {
      result.latestAlerts = ESWrapperService.searchJson(indexes_to_search,es_query,result.offset,result.max,'evtTimestamp','desc');
      result.totalAlerts = result.latestAlerts?.getHits()?.totalHits
      result.rows = buildSubscriptionInfo(result.latestAlerts?.getHits()?.getHits())
    }
    catch ( Exception e ) {
      log.error("Problem with query",e);
    }

    render(template:'/subscriptions/atom', model:[result:result],contentType: "text/xml", encoding: "UTF-8", contextPath: '/')
  }

  private List buildSubscriptionInfo(rows) {
    List result = []
    rows.each { row ->
      Map<String, Object> src = row.getSource()
      Map new_entry = [:]
      new_entry.identifier=src.AlertBody.identifier
      new_entry.url=src.AlertMetadata.SourceUrl

      def info_elements = src.AlertBody.info instanceof List ? src.AlertBody.info : [ src.AlertBody.info ]

      def first_description = null;
      def first_title = null;

      info_elements.each { info ->
        if ( ( first_description == null ) && ( info.description != null ) )
          first_description = info.description;
        if ( ( first_title == null ) && ( info.headline != null ) )
          first_title = info.headline;

        new_entry.title=first_title
        new_entry.description=first_description
      }

      result.add(new_entry);
    }
    result
  }

  @Secured(['ROLE_ADMIN', 'IS_AUTHENTICATED_FULLY'])
  def addHook() {
    log.debug("addHook ${params}");
    if ( params.newHookUrl &&
         params.newHookUrl.length() > 0 ) {
      Subscription s = Subscription.findBySubscriptionId(params.id);
      WebHook new_hook = new WebHook(ownerSubscription: s, hookUrl: params.newHookUrl)
      new_hook.save(flush:true, failOnError:true);
    }
    redirect(action:'details', id:params.id);
  }
}

CAPAggregator/grails-app/views/subscriptions/details.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title></title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />
</head>
<body>

  <g:if test="${subscription!=null}">
    <div class="container-fluid">
      <div class="row">
        <div class="container-fluid">
          <h1>${subscription.subscriptionId} / ${subscription.subscriptionName}</a></h1>
  
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Subscription Info</h3>
            </div>
            <div class="panel-body form-horizontal container-fluid">
              <div class="row">
                <div class="col-md-9">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="form-group">
                        <label class="col-sm-3 control-label">URL</label>
                        <div class="col-sm-9"><p class="form-control-static"><a href="${subscription.subscriptionUrl}">${subscription.subscriptionUrl}</a></p></div>
                      </div>
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Alert Count</label>
                        <div class="col-sm-9"><p class="form-control-static">${totalAlerts?:0} (${rows?.size()?:0} shown)</p></div>
                      </div>
                    </div>
    
    
                    <div class="col-md-4">
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Filter Type</label>
                        <div class="col-sm-9"><p class="form-control-static">${subscription.filterType}</p></div>
                      </div>
    
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Filter Geometry</label>
                        <div class="col-sm-9"><p class="form-control-static" id="sub-filter-geom" data-sub-geom="${subscription.filterGeometry}" >${subscription.filterGeometry}</p></div>
                      </div>
                    </div>

                    <div class="col-md-4">
                      <div class="form-group">
                        <label class="col-sm-3 control-label">Params</label>
                        <div class="col-sm-9"><p class="form-control-static"><ul>
                            <li>langFilter:<strong>${subscription.languageOnly}</strong></li>
                            <li>priorityFilter:<strong>${subscription.highPriorityOnly}</strong></li>
                            <li>officialFilter:<strong>${subscription.officialOnly}</strong></li>
                            <li>xpathFilterId:<strong>${subscription.xPathFilterId}</strong></li>
                          </ul>
                        </p></div>
                      </div>
                    </div>

                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="col-sm-2 control-label">WebHooks</label>
                        <div class="col-sm-10"><p class="form-control-static"><ul>
                          <g:each in="${subscription.hooks}" var="webhook">
                            <div class="card">
                              <div class="card-body">
                                ${webhook.hookUrl}
                              </div>
                            </div>
                          </g:each>
                        </div>
                      </div>
                    </div>
                

                    <sec:ifLoggedIn>
                      <div class="card">
                        <div class="card-body">
                          <g:form controller="subscriptions" id="${params.id}" action="addHook" method="get" class="container">
                            <div class="input-group">
                                <span class="input-group-addon">Add Web Hook:</span>
                                <input type="text" name="newHookUrl" class="form-control " placeholder="Text input" value="">
                                <span class="input-group-btn">
                                    <button type="submit" class="btn btn-search">Add</button>
                                </span>
                            </div>
                          </g:form>
                        </div>
                      </div>
                    </sec:ifLoggedIn>

                  </div>
                </div>

                <div class="col-md-3">
                  <div class="MapWithFeatures" id="subscription_map" data-features="[]"></div>

                </div>
    
              </div>


            </div>
          </div>
  
        </div>
      </div>
  
      <div class="row">
  
        <div class="container-fluid" style="vertical-align: middle; text-align:center;">
  
  
          <g:form controller="subscriptions" id="${params.id}" action="details" method="get" class="container">
            <div class="input-group">
                <input type="text" name="q" class="form-control " placeholder="Text input" value="${params.q}">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-search">Search</button>
                </span>
            </div>
          </g:form>
  
          <div>
            Showing alerts ${(offset?:0)+1} to ${java.lang.Math.min(((offset?:0)+(max?:10)),(totalAlerts?:0))} of ${totalAlerts?:0}
          </div>
  
          <div class="pagination">
            <g:paginate controller="subscriptions" action="details" params="${[id:params.id]}" total="${totalAlerts?:0}" next="Next" prev="Previous" omitNext="false" omitPrev="false" />
          </div>
  
        </div>
        <div class="container-fluid">
  
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
              </tr>
            </thead>
            <tbody>
              <g:each in="${rows}" var="alert" status="s">
                <g:set var="alsrc" value="${alert.getSourceAsMap()}"/>
                <tr>
                  <td>
                    <div class="MapWithAlert" id="map_for_${s}"
                                              data-alert-id="${alert.getId()}" 
                                              data-alert-body="${alsrc.AlertBody as grails.converters.JSON}"></div>
                  </td>
                  <td>
                    <g:set var="ifo_list" value="${alsrc.AlertBody.info instanceof List ? alsrc.AlertBody.info : [ alsrc.AlertBody.info ]}"/>
                    <g:each in="${ifo_list}" var="ifo">
                      <h3>${ifo.headline}</h3>
                    </g:each>
  
                    <div class="form-horizontal">
                      <div class="form-group"> <label class="col-sm-2 control-label">Alert Identifier</label> 
                        <div class="col-sm-10"><p class="form-control-static"><g:link controller="alert" action="details" id="${alsrc.AlertBody.identifier}">${alsrc.AlertBody.identifier}</g:link><g:if test="${alsrc.AlertMetadata.Expires != null}">&nbsp;(Expires: ${alsrc.AlertMetadata.Expires})</g:if></p></div>
                      </div>
                      
                      <div class="form-group"> 
                        <label class="col-sm-2 control-label">Alert Sender</label> 
                        <div class="col-sm-10">
                          <p class="form-control-static">${alsrc.AlertBody.sender} (via feed 
                            <a href="/feedFacade/sourcefeed/feed/${alsrc.AlertMetadata.sourceFeed}">${alsrc.AlertMetadata.sourceFeed}</a>)</p>
                        </div> 
                      </div>
                      <div class="form-group"> <label class="col-sm-2 control-label">Times:</label> <div class="col-sm-10">
                          <table class="table table-striped">
                            <tr><th>Date on alert</th><td>${alsrc.AlertBody.sent}</td></tr>
                            <g:each in="${alsrc.AlertMetadata.CCHistory}" var="he">
                              <tr><th>${he.event}</th><td><g:formatDate format="yyyy-MM-dd HH:mm:ss.SSS z" date="${new Date(he.timestamp)}" timeZone="UTC"/></td></tr>
                            </g:each>
                          </table>
                       </div> </div>
                      <div class="form-group"> <label class="col-sm-2 control-label">Source</label> <div class="col-sm-10"><p class="form-control-static">${alsrc.AlertMetadata.SourceUrl}</p></div> </div>
                      <div class="form-group"> <label class="col-sm-2 control-label">Matched Subscriptions</label> <div class="col-sm-10"><p class="form-control-static">
                       <g:each in="${alsrc.AlertMetadata.MatchedSubscriptions}" var="ms"> <g:link controller="subscriptions" action="details" id="${ms}">${ms}</g:link> &nbsp; </g:each> </p></div> 
                      </div>
                      <div class="form-group"> <label class="col-sm-2 control-label">Tags</label> 
                        <div class="col-sm-10">
                          <p class="form-control-static"><g:each in="${alsrc.AlertMetadata.tags}" var="tag">${tag} &nbsp; </g:each>
                        </div> 
                      </div>
                      <g:each in="${ifo_list}" var="ifo">
                        <div class="form-group"> <label class="col-sm-2 control-label">Information</label> <div class="col-sm-10">
                              <div class="form-group"> <label class="col-sm-2 control-label">Language</label> <div class="col-sm-10"><p class="form-control-static">${ifo.language}</p></div> </div>
                              <div class="form-group"> <label class="col-sm-2 control-label">Headline</label> <div class="col-sm-10"><p class="form-control-static">${ifo.headline}</p></div> </div>
                              <div class="form-group"> <label class="col-sm-2 control-label">Description</label> <div class="col-sm-10"><p class="form-control-static">${ifo.description}</p></div> </div>
                              <div class="form-group"> <label class="col-sm-2 control-label">Action</label> <div class="col-sm-10"><p class="form-control-static">${ifo.action}</p></div> </div>
                        </div>
                      </g:each>
                    </div>
  
                  </td>
                </tr>
              </g:each>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </g:if>
  <g:else>
    <div class="container-fluid">
      <div class="row">
        No Unfiltered Subscription Found. Please load the default subscriptions using the <g:link controller="admin" action="syncSubList">admin - load subscription</g:link> feature
      </div>
    </div>
  </g:else>

<asset:script type="text/javascript">
  if (typeof jQuery !== 'undefined') {
    (function($) {

      let sub_geom = $('#sub-filter-geom').data("sub-geom");
      let sub_poly = [];

      console.log("Sub poly is %o",sub_geom);

      $('.MapWithAlert').each(function(i,obj) {
        initMap(obj.id, $(obj).data("alert-body"));
      });

      $('.MapWithFeatures').each(function(i,obj) {
        console.log("Map with features");
        mapWithGeoJsonFeatures(obj.id, sub_geom);
      });
    })(jQuery);
  }

</asset:script>

</body>
</html>

CAPAggregator/grails-app/views/subscriptions/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>CAP Aggregator: Search through all currently known subscriptions</title>

    <asset:link rel="icon" href="favicon.ico" type="image/x-ico" />
</head>
<body>

  <div class="container-fluid">
    <div class="row">
      <div class="container" style="vertical-align: middle; text-align:center;">

        <h1>Subscriptions (${totalSubscriptions} found)</h1>

        <p>This page provides a searchable index of all the currently known CAP subscriptions. Subscriptions are virtual feeds that collect alerts from
           all known providers which intersect with a given geographical area. You can search using full text in the subscription definitions. Use the unfiltered feed to
           drink from the firehose.</p>

        <g:form controller="subscriptions" action="index" method="get" class="container">
          <div class="input-group">
              <input type="text" name="q" class="form-control " placeholder="Enter any keywords for your subscription, eg Sheffield" value="${params.q}">
              <span class="input-group-btn">
                  <button type="submit" class="btn btn-search">Search</button>
              </span>
          </div>
        </g:form>

        <div class="pagination">
          <g:paginate controller="subscriptions" action="index" total="${totalSubscriptions}" next="Next" prev="Previous" omitNext="false" omitPrev="false" />
        </div>

      </div>
    </div>
    <div class="row">
      <div class="container-fluid">

        <table class="table table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <th>SLUG</th>
              <th>Name</th>
              <th>URL</th>
              <th>Type</th>
              <th>Filter</th>
              <th>Geom</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <g:each in="${subscriptions}" var="${sub}">
              <tr>
                <td>${sub.id}</td>
                <td><g:link controller="subscriptions" action="details" id="${sub.subscriptionId}">${sub.subscriptionId}</g:link></td>
                <td>${sub.subscriptionName}</td>
                <td>${sub.subscriptionUrl}</td>
                <td>${sub.filterType}</td>
                <td>
                  <ul>
                    <li>FilterId: ${sub.xPathFilterId}</li>
                    <li>XPath: ${sub.xPathFilter}</li>
                    <li>Language: ${sub.languageOnly ?: 'all'}</li>
                    <li>High Priority: ${sub.highPriorityOnly ?: 'all'}</li>
                    <li>Official: ${sub.officialOnly ?: 'all'}</li>
                  </ul>
                </td>
                <td>${sub.filterGeometry}</td>
                <td>
                  <sec:ifAnyGranted roles="ROLE_ADMIN">
                    <g:link controller="subscriptions" action="touch" class="btn btn-primary" role="button" id="${sub.id}">Touch</g:link>
                  </sec:ifAnyGranted>
                </td>
              </tr>
            </g:each>
          </tbody>
        </table>
      </div>
    </div>
</body>
</html>